baseURL = "https://zoetrope.github.io/kubebuilder-training"
publishDir = "docs"

languageCode = "ja-jp"
DefaultContentLanguage = "ja"
hasCJKLanguage = true
metaDataFormat = "yaml"
defaultContentLanguage = "ja"

title = "Kubebuilder Training"
theme = "techdoc"

[params]
    menu_style = "open-menu"

[markup]
  defaultMarkdownHandler = "blackfriday"
