apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: markdown-viewer-metrics-reader
subjects:
  - kind: ServiceAccount
    name: prometheus-prometheus-oper-prometheus
    namespace: prometheus
